apiVersion: apps/v1
kind: Deployment
metadata:
  name: spe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spe-app
  template:
    metadata:
      labels:
        app: spe-app
    spec:
      # 1. Create a shared temporary folder for this Pod
      volumes:
        - name: shared-data
          emptyDir: {}

      containers:
        # --- Edge Inference Service ---
        - name: edge-infer
          image: smoothlake67/spe-mlops:latest
          command: ["python", "app/edge_infer.py"]
          env:
            - name: MQTT_BROKER
              value: "broker"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          # Mount the shared folder here
          volumeMounts:
            - name: shared-data
              mountPath: /app/data

        # --- Publisher Service ---
        - name: publisher
          image: smoothlake67/spe-mlops:latest
          command: ["python", "devices/publisher.py"]
          env:
            - name: MQTT_BROKER
              value: "broker"
          # Mount the shared folder here too
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"

        # --- Dashboard Service ---
        - name: dashboard
          image: smoothlake67/spe-mlops:latest
          command:
            [
              "streamlit",
              "run",
              "dashboard/dashboard.py",
              "--server.port",
              "8501",
              "--server.address",
              "0.0.0.0",
            ]
          ports:
            - containerPort: 8501
          # Mount the shared folder here too (so dashboard can see the CSV)
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  type: NodePort
  selector:
    app: spe-app
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30002
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: spe-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: spe-app
#   minReplicas: 1
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 50
