$ANSIBLE_VAULT;1.1;AES256
37616633626237626330353862316337636364316565343035346230333564343732333061343430
3562383466666636666234653038396263303639353261640a623233623766623033303036303938
66666166633336666536653561376661353437386164313163626132323363353036306562383336
6334373137316663330a396430386563666663616236343333336634663661616563313964626430
37666435636232356665386538323237393465653634306233393565333464663961653836376537
32633036396265383861636663323365336431666432326432373037396364376261373234613531
34343463643061323437616331316630323761353061376130323762306465313936356266633734
35353433393361643230346166303862373363343166393835303239393161613434396132343939
61643166393033633462393735653064663135616534333261356335353762323961
